config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20 }
  validates :start_at, presence: true
  validates :end_at,comparison: { greater_than_or_equal_to: :start_at, allow_blank: true }, presence: true
  validates :memo, length: { maximum: 500 }
  validates :is_all_day, inclusion: [true, false]

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
    def index
      @tasks = Task.all
    end
  

  def new
    @task =Task.new
  end

  def create
    @task= Task.new(task_params)
    if @task.save
      flash[:notice] = "タスクを登録しました。"
      redirect_to :tasks
    else 
      flash.now[:mistake] = "タスクの登録に失敗しました。"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @task = Task.find_by(id:params[:id])
  end

  def edit
    @task = Task.find_by(id:params[:id])
  end

  def update
    @task = Task.find_by(id:params[:id])

    if @task.update(task_params)
      flash[:success] = "タスクを編集しました。"
      redirect_to :tasks
    else 
      flash.now[:failure] = "タスクの編集に失敗しました。"
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
    flash[:erace] = "予定を削除しました"
    redirect_to :tasks
    else
      redirect_to :tasks
    end  
  end


  private
  def task_params
    params.require(:task).permit(
    :title,
    :start_at,
    :end_at,
    :is_all_day,
    :memo
    )
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_error_messages.html.erb
<% if @task.errors.any? %>
  <div class="alert alert-warning">
    <% @task.errors.full_messages.each do |message| %>
    <ul>
        <li><%= message %></li>
    </ul>
      <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskmanage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="p-3 mb-2 bg-dark text-center">
        <%= link_to("スケジュール管理アプリ","/",class:"text-white text-decoration-none") %>
      </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
  <div class="form_container bg-white m-5 mx-auto p-3 w-50">
    <%= form_with model: @task,local: true do | f | %>
    <%= render "/layouts/error_messages", model: f.object %>

    <div class="form-group">
      <%= f.label "タイトル",class: "fw-bold" %>
      <%= f.text_field :title, placeholder: "タイトル", class: "form-control" %>
    </div>

    <div class="form-group grid gap-0 column-gap-3">
      <div class="start-form d-flex flex-column">
      <%= f.label "開始日",class: "fw-bold" %>
      <%= f.date_field :start_at, class:"p-2 g-col-6 border border-black border-opacity-10 rounded" %>
      </div>
      <div class="end-form d-flex flex-column">
      <%= f.label "終了日",class: "fw-bold" %>
      <%= f.date_field :end_at, class:"p-2 g-col-6 border border-black border-opacity-10 rounded"  %>
      </div>
    </div>
    <div class="form-group mb-2">
      <%= f.check_box :is_all_day,{},"true","false"%>
      <%= f.label "終日の場合はチェックを入れます" %>

    </div>
    <div class="form-group d-flex flex-column">
      <%= f.label "スケジュールメモ",class: "fw-bold" %>
      <%= f.text_area :memo, placeholder: "メモを入力する", class: "form-control", rows: 5 %>
    </div>    
    <div class="d-flex justify-content-end mt-2">
      <%= f.submit :"保存", class: "btn btn-primary p-2" %>
      <% end %>
      
      <%= link_to "キャンセル", tasks_path, class: "btn btn-secondary ms-2" %>
    </div>
    
    
  </div>    

app/views/tasks/edit.html.erb
<div class="p-3 bg-light text-dark">
  <h3 class="mt-2 mx-auto w-50">予定の編集</h3>
  <div class ="text-center text-danger fs-5 fw-bold" > 
    <% if flash[:failure]%>
      <p><%= flash[:failure]%></p>
      <% end%>  
  </div>    
    <%= render "shared/form" %>
      

</div>

app/views/tasks/index.html.erb
<div class="p-3 mb-2 bg-light text-dark">
  
  <div class="m-5">
    <div class="d-flex justify-content-between mb-2">
      <div class="fw-bold">予定一覧</div>
      <div class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16"
        color="white">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>
        <%= link_to("新規追加","/tasks/new",class: "text-white text-decoration-none") %>
      </div>  
    </div>
  <table class="table table-hover p-4 bg-white text-dark">
  <tbody>
      <tr class="fw-bold">
        <td>ID</td>
        <td>タイトル</td>
        <td>開始日</td>
        <td>終了日</td>
        <td>終日</td>
        <td>更新日時</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      
      
      <tr>
      <% @tasks.each do | task |%>
        <td><%= task.id %></td>
        <td><%= task.title %></td>
        <td><%= task.start_at.to_s(:date_jp) %></td>
        <td><%= task.end_at.to_s(:date_jp) %></td>
        <td>
            <%if task.is_all_day == true %>
                ○

            <%elsif task.is_all_day == false %>
            
            <% end %>
        </td>
        <td>
          <%= task.updated_at.to_s(:datetime_jp) %>
        </td>
        <td>
          <%= link_to("詳細","/tasks/#{task.id}") %>
        </td>
        <td>
        <%= link_to("編集","/tasks/#{task.id}/edit") %>
        </td>
        <td>
        <%= button_to "削除",task_path(task.id),{ method: :delete, class: "text-primary bg-white text-decoration-underline border border-0", form: { data: { turbo_confirm: "本当に削除しますか？" } } } %>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
<!--フラッシュメッセージ表示view-->  
  <div class ="text-center text-success fs-5 fw-bold" > 
    <% if flash[:success]%>
    <%= flash[:success]%>
    <% elsif flash[:notice]%>
    <%= flash[:notice] %>
    <% elsif flash[:erace]%>
    <%= flash[:erace] %>
    <% end%>  
  </div>  
  <div class="bg-white p-2 mt-5 d-flex justify-content-between">
      <p class="fw-bold fs-3"><%= "予定合計#{Task.count}件"%></p>
      <p class="fw-bold fs-3 opacity-25"><%= "本日の日付#{Date.today}"%></p>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="p-3 bg-light text-dark">
  <h3 class="mt-2 mx-auto w-50">予定の新規追加</h3>
    <div class ="text-center text-danger fs-5 fw-bold" > 
      <% if flash[:mistake]%>
      <p><%= flash[:mistake]%></p>
      <% end%>  
    </div>  
    <%= render "shared/form" %>
  
</div>

app/views/tasks/show.html.erb
<div class="p-3 bg-light">
  <div class ="m-3 position-relative">
    <%= link_to "←  一覧へ戻る","/"%>
    <div class="btn btn-outline-primary position-absolute top-0 end-0">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
      <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
      </svg>
      <%= link_to "編集","/tasks/#{@task.id}/edit",class: "text-decoration-none"%>
    </div> 
  </div> 
  <div class="container bg-white m-5 mx-auto p-3 w-50">  
    <p class="fs-4 fw-bold">
        <%= @task.title%>
    </p>
  <table class="table">
      <tbody>
          <tr>
              <td class="table-secondary">開始日</td>
              <td><%= @task.start_at.to_s(:date_jp)%></td>
          </tr>
          <tr>
              <td class="table-secondary">終了日</td>
              <td><%= @task.end_at.to_s(:date_jp)%></td>
          </tr>
          <tr>
              <td class="table-secondary">終日</td>
              <td>
                <% if @task.is_all_day == true %>
                  ○
                <% elsif @task.is_all_day == false %>

                <% end %>
              </td>
          </tr>
          <tr>
              <td class="table-secondary">スケジュールメモ</td>
              <td><%= @task.memo%></td>
          </tr>
      </tbody>
  </table>
  </div>
</div>  